# Publish all joint states -----------------------------------
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    left_wheel_joint_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: wheel_left_joint  
      pid: {p: 00.1, i: 0.00001, d: 0.0001}

    right_wheel_joint_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: wheel_right_joint 
      pid: {p: 100.0, i: 0.1, d: 10.0}
